### PR TITLE
Bug fixes

### LINKED ISSUE #74: Shortcuts do not work on macOS
**Describe the bug**
When you are on macOS: shortcuts to copy, cut, paste, mark, etc. text in input fields do not work.

**To Reproduce**
1. Go to login screen
2. Try to paste, copy, cut, mark, etc. text to / from any field

**Expected behavior**
Past, copy, cut, mark shortcuts should work properly.

**Screenshots**

**Please complete the following information:**

```
Version: 1.0.0
Commit: 50912ab669d7e1e6056ecdb7233d03d42ebfa591
Date: 2021-06-12T16:06:48.000Z (0 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

**Additional context**

### PR DESCRIPTION
**Pull request by noctera**
| Status  | Type  |
| :---: | :---: |
| :white_check_mark: Ready | Bug |

## Motivation and Context
Some bug fixes and UX improvements

To do:

- [x] put the description only on the translated side of the card
- [x] change docs url in menu
- [x] show current language on card side while query
- [x] add translations for "Add"-Button in select component
- [x] use shortcuts for "add vocab" page. (UX improvements)
- [ ] ~~Indicator in library that shows how many vocabs exist in package/group~~
- [ ] ~~guide closes after adding a package when the account has been registered the first time~~  -> Couldn't reproduce this bug anymore
- [ ] ~~ability to skip specific steps of the guide after opening it the second time~~
- [x] sign out button has different animation
- [ ] ~~change guide pictures to .svg~~
- [ ] ~~add russian to language selector~~
- [x] #74

Crossed out tasks will be resolved in following PRs

## Checklist

- [x] I have read the **CONTRIBUTING** document.
- [x] I have considered the accessibility of my changes (i.e. did I add proper content descriptions to images, or run my changes with talkback enabled?)
- [x] I have documented my code if needed

## Resolves

fixes #74

### CODE REVIEW

File: src/Components/Button/Button.jsx [hunk 1]
```diff
@@ -12,6 +12,8 @@ const Button = ({
   onClick = () => null,
   children,
   className = "",
+  tabIndex = null,
+  type = null,
```
Comment (luwol03) [inline src/Components/Button/Button.jsx:16]: use 
```jsx
{...props}
```

File: src/Components/Form/ArrayTextInput/ArrayTextInput.jsx [hunk 2]
```diff
@@ -69,6 +69,28 @@ const ArrayTextInput = ({
     }
   }, [data]);
 
+  useEffect(() => {
+    const listener = (event) => {
+      if (event.keyCode === 40) {
```
Comment (luwol03) [inline src/Components/Form/ArrayTextInput/ArrayTextInput.jsx:74]: can you add comments, which key 40 and 38 is?

**Review by luwol03 — APPROVED** [review]
